[project]
name = "service-status-indicator-agent"
version = "0.1.0"
description = "The agent backend of the Service Status Indicator"
authors = [
    {name = "RemiZlatinis",email = "remizlatinis@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "websockets (>=15.0.1,<16.0.0)",
    "watchdog (>=6.0.0,<7.0.0)",
    "click (>=8.2.1,<9.0.0)",
    "pytest (>=8.4.1,<9.0.0)",
    "pydantic (>=2.0.0,<3.0.0)"
]

[tool.poetry]
package-mode = false

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
